// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhkzqdvfwiyhedreffmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oa3pxZHZmd2l5aGVkcmVmZm14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjQ1NzIsImV4cCI6MjA2MjIwMDU3Mn0.np4PlI0g3YJYGOaDYDJyTOCbdZnV93vtOlrDFandwU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);